name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.202'
      - name: Restore
        run: dotnet restore noo.api.sln
      - name: Verify formatting
        run: dotnet format --verify-no-changes
      - name: Build
        run: dotnet build src/Noo.Api/Noo.Api.csproj -c Release --no-restore
      - name: Test unit
        run: dotnet test tests/Noo.UnitTests/Noo.UnitTests.csproj -c Release --verbosity normal
      - name: Test integration
        if: ${{ hashFiles('tests/Noo.IntegrationTests/Noo.IntegrationTests.csproj') != '' }}
        run: dotnet test tests/Noo.IntegrationTests/Noo.IntegrationTests.csproj -c Release --verbosity normal
